apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2       #Количество контейнеров
  selector:
    matchLabels:
      app: my-app   #Селектор для поиска "своих" подов
  template:         #Шаблон pod-а
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.12
          name: nginx
          ports:
            - containerPort: 80
